(define (re-compile-pattern       . arguments) (display "Not Implemented"))
(define (re-string-match          . arguments) (display "Not Implemented"))
(define (re-substring-matchx      . arguments) (display "Not Implemented"))
(define (re-string-search-forward . arguments) (display "Not Implemented"))
(define (re-match-start-index     . arguments) (display "Not Implemented"))
(define (re-match-end-index       . arguments) (display "Not Implemented"))
(define (re-match-extract         . arguments) (display "Not Implemented"))
(define (regexp-group             . arguments) (display "Not Implemented"))
