(define (re-compile-pattern       . arg) (error "Not implemented" re-compile-pattern))
(define (re-string-match          . arg) (error "Not implemented" re-string-match))
(define (re-substring-matchx      . arg) (error "Not implemented" re-substring-matchx))
(define (re-string-search-forward . arg) (error "Not implemented" re-string-search-forward))
(define (re-match-start-index     . arg) (error "Not implemented" re-match-start-index))
(define (re-match-end-index       . arg) (error "Not implemented" re-match-end-index))
(define (re-match-extract         . arg) (error "Not implemented" re-match-extract))
(define (regexp-group             . arg) (error "Not implemented" regexp-group))
